# Generated by Django 5.2.3 on 2025-06-30 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LDGS_NM', models.CharField(max_length=255)),
                ('LDGS_ADDR', models.CharField(max_length=255)),
                ('LDGS_ROAD_NM_ADDR', models.CharField(max_length=255)),
                ('GSRM_SCALE_CN', models.CharField(max_length=255)),
                ('LDGS_GRAD_VALUE', models.CharField(max_length=255)),
                ('LDGMNT_TY_NM', models.CharField(max_length=255)),
                ('LDGS_AVRG_PRC', models.FloatField(blank=True, null=True)),
                ('LDGS_MIN_PRC', models.FloatField(blank=True, null=True)),
                ('LDGS_MXMM_PRC', models.FloatField(blank=True, null=True)),
                ('LDGS_AVRG_SCORE_CO', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Category', models.CharField(max_length=255)),
                ('Score', models.FloatField(blank=True, null=True)),
                ('Review_Num', models.IntegerField()),
                ('Link', models.URLField(max_length=500)),
                ('Addr', models.CharField(max_length=500)),
                ('Area', models.CharField(max_length=500)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
