# Generated by Django 5.2.3 on 2025-07-03 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_actor_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Drama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(max_length=100, verbose_name='미디어타입')),
                ('title', models.CharField(max_length=255, verbose_name='제목')),
                ('place_name', models.CharField(max_length=255, verbose_name='장소명')),
                ('place_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='장소타입')),
                ('place_description', models.TextField(blank=True, null=True, verbose_name='장소설명')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='주소')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='위도')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='경도')),
                ('address_region', models.CharField(blank=True, max_length=100, null=True, verbose_name='주소_지역명')),
                ('actors', models.ManyToManyField(related_name='dr배우이름', to='myapp.actor')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(max_length=100, verbose_name='미디어타입')),
                ('title', models.CharField(max_length=255, verbose_name='제목')),
                ('place_name', models.CharField(max_length=255, verbose_name='장소명')),
                ('place_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='장소타입')),
                ('place_description', models.TextField(blank=True, null=True, verbose_name='장소설명')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='주소')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='위도')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='경도')),
                ('address_region', models.CharField(blank=True, max_length=100, null=True, verbose_name='주소_지역명')),
                ('actors', models.ManyToManyField(related_name='mo배우이름', to='myapp.actor')),
            ],
        ),
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(max_length=100, verbose_name='미디어타입')),
                ('title', models.CharField(max_length=255, verbose_name='제목')),
                ('place_name', models.CharField(max_length=255, verbose_name='장소명')),
                ('place_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='장소타입')),
                ('place_description', models.TextField(blank=True, null=True, verbose_name='장소설명')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='주소')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='위도')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='경도')),
                ('address_region', models.CharField(blank=True, max_length=100, null=True, verbose_name='주소_지역명')),
                ('artists', models.ManyToManyField(related_name='아티스트명', to='myapp.artist')),
            ],
        ),
        migrations.DeleteModel(
            name='Content',
        ),
    ]
