# Generated by Django 5.2.3 on 2025-07-03 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_artist_drama_movie_singer_delete_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='LDGS_AVRG_PRC',
        ),
        migrations.AlterField(
            model_name='drama',
            name='actors',
            field=models.ManyToManyField(related_name='드라마배우이름', to='myapp.actor'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='GSRM_SCALE_CN',
            field=models.CharField(max_length=255, verbose_name='규모'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='LDGMNT_TY_NM',
            field=models.CharField(max_length=255, verbose_name='숙박유형'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='LDGS_ADDR',
            field=models.CharField(max_length=255, verbose_name='지역명'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='LDGS_AVRG_SCORE_CO',
            field=models.FloatField(blank=True, null=True, verbose_name='평균평점'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='LDGS_GRAD_VALUE',
            field=models.CharField(max_length=255, verbose_name='성급'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='LDGS_MIN_PRC',
            field=models.FloatField(blank=True, null=True, verbose_name='최저가격'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='LDGS_MXMM_PRC',
            field=models.FloatField(blank=True, null=True, verbose_name='최고가격'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='LDGS_NM',
            field=models.CharField(max_length=255, verbose_name='숙박명'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='LDGS_ROAD_NM_ADDR',
            field=models.CharField(max_length=255, verbose_name='도로명주소'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='위도'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='경도'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(related_name='영화배우이름', to='myapp.actor'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='Addr',
            field=models.CharField(max_length=500, verbose_name='주소'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='Area',
            field=models.CharField(max_length=500, verbose_name='지역명'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='Category',
            field=models.CharField(max_length=255, verbose_name='카테고리'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='Link',
            field=models.URLField(max_length=500, verbose_name='웹사이트'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='Name',
            field=models.CharField(max_length=255, verbose_name='식당이름'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='Review_Num',
            field=models.IntegerField(verbose_name='리뷰수'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='Score',
            field=models.FloatField(blank=True, null=True, verbose_name='별점'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='위도'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='경도'),
        ),
    ]
