# Generated by Django 5.2.3 on 2025-07-03 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_hotel_ldgs_avrg_prc_alter_drama_actors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drama',
            name='actors',
            field=models.ManyToManyField(related_name='DrActors', to='myapp.actor', verbose_name='드라마배우 이름'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(related_name='MoActors', to='myapp.actor', verbose_name='영화배우 이름'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='Review_Num',
            field=models.IntegerField(verbose_name='리뷰 수'),
        ),
    ]
