# Generated by Django 5.2.3 on 2025-07-03 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_drama_actors_alter_movie_actors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='LDGS_MIN_PRC',
            field=models.FloatField(blank=True, null=True, verbose_name='최소가격'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='LDGS_MXMM_PRC',
            field=models.FloatField(blank=True, null=True, verbose_name='최대가격'),
        ),
    ]
